<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RnD_CI_Windows" name="com.YouMagicPro.LKA_tests.VoiceMenuEmptyNameTextFieldTest" tests="1" failures="0" timestamp="10 Dec 2012 05:23:33 GMT" time="19.540" errors="1">
  <testcase name="voiceMailEmptyNameTextFieldTest_C19851" time="19.540" classname="com.YouMagicPro.LKA_tests.VoiceMenuEmptyNameTextFieldTest">
    <error type="java.lang.AssertionError" message="expected [Ќазвание меню об€зательно дл€ заполнени€.] but found [ѕользование услугой приостановлено.]">
      <![CDATA[java.lang.AssertionError: expected [Ќазвание меню об€зательно дл€ заполнени€.] but found [ѕользование услугой приостановлено.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.YouMagicPro.LKA_tests.TestBase.assertEquals(TestBase.java:51)
	at com.YouMagicPro.LKA_tests.VoiceMenuEmptyNameTextFieldTest.voiceMailEmptyNameTextFieldTest_C19851(VoiceMenuEmptyNameTextFieldTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- voiceMailEmptyNameTextFieldTest_C19851 -->
</testsuite> <!-- com.YouMagicPro.LKA_tests.VoiceMenuEmptyNameTextFieldTest -->
